;;;;;;;;;;;;;;;;
;GAME VARIABLES;
;;;;;;;;;;;;;;;;
;ZP vars
;Temps: $00-$17
ScrollInitCounter	.equ $18
LevelGlobalTimer	.equ $1A
NMIMutex		.equ $1B
GameMode		.equ $1C
GameSubmode		.equ $1D
BlackScreenTimer	.equ $1E
VRAMBufferOffset	.equ $1F
CurLevel		.equ $20
TempBankSwitchMutex	.equ $21
BankSwitchReturnAddr	.equ $22
EnemyOAMStartIndex	.equ $24
PRNGDataPointer		.equ $28
;Unused: $2A
CurScreen		.equ $2B
ScrollXVelHi		.equ $2C
ScrollXVelLo		.equ $2D
ScrollXAccel		.equ $2E
ScrollYVelHi		.equ $2F
ScrollYVelLo		.equ $30
ScrollYAccel		.equ $31
ScrollUpdateFlag	.equ $32
AreaScrollFlags		.equ $33
CurCharacter		.equ $34
CurArea			.equ $37
AreaDirectionFlags	.equ $38
LevelAreaInfoPointer	.equ $39
HardModeFlag		.equ $3B
CharacterPowerMax	.equ $3C
CharacterPowerCur	.equ $41
ScoreCurrent		.equ $46
ScoreTop		.equ $48
NumLives		.equ $4C
CurPalette		.equ $4D
PlayerPaletteOffset	.equ $4E
UpdateMetatilePos	.equ $4F
UpdateMetatileID	.equ $55
UpdateMetatileProps	.equ $5B
UpdateMetatileCount	.equ $61
ItemCollectedBits	.equ $62
EnemyTriggeredBits	.equ $64
LevelAreaNum		.equ $66
IRQBufferCollisionFlag	.equ $67
PlatformEnableFlag	.equ $68
BGFireArchTimer		.equ $69
UpdateVRAMStripCount	.equ $6A
UpdateVRAMStripID	.equ $6B
PlatformXVel		.equ $71
BankSwitchMutex		.equ $72
ScrollUpdateDisableFlag	.equ $73
TempLastBankSwitch	.equ $74
LastBankSwitch		.equ $75
SoundMutex		.equ $76
LevelLoadMode		.equ $77
PlatformScrollXVel	.equ $78
LevelBank		.equ $79
CollBufferPointer	.equ $7A
FloatingLogJumpFlag	.equ $7C
ControlPlayerMutex	.equ $7D
LevelBGPointer		.equ $7E
LevelAttrPointer	.equ $80
LevelTilePointer	.equ $82
TileCollRange00		.equ $84
TileCollRange01		.equ $87
TempIRQEnableFlag	.equ $8A
IRQEnableFlag		.equ $8B
TempIRQCount		.equ $8C
IRQCount		.equ $8D
IRQIndex		.equ $8E
IRQWaitFlag		.equ $8F
TempIRQBufferHeight	.equ $90
IRQBufferHeight		.equ $98
TempIRQBufferScrollX	.equ $A0
IRQBufferScrollX	.equ $A8
TempIRQBufferScrollY	.equ $B0
TempIRQBufferScrollHi	.equ $B8
IRQBufferAddrHi		.equ $C0
IRQBufferAddrLo		.equ $C8
IRQBufferPlatformXVel	.equ $D0
ScrollDisableFlag	.equ $D8
ScrollDirectionFlag	.equ $D9
IceMeltedBits		.equ $DA
EnemyGrabbingMode	.equ $DB
LavaWormGrabFlag	.equ $DC
GravityAreaMode		.equ $DD
OnEscapePodFlag		.equ $DE
EscapePodDirection	.equ $DF
TempMetatileID		.equ $E0
AutoEscapePodFlag	.equ $E1
CrusherAreaFlag		.equ $E2
OAMPrevAttr		.equ $E3
;Temps: $E4-$EB
TempSoundDataIndex	.equ $EC
TempSoundJumpPointer	.equ $EE
TempSoundDataPointer	.equ $F0
TempSoundInitPointer	.equ $F2
JoypadDown		.equ $F5
IRQBufferMutex		.equ $F6
JoypadCur		.equ $F7
TempMirror_PPUSCROLL_Y	.equ $FC
TempMirror_PPUSCROLL_X	.equ $FD
Mirror_PPUMASK		.equ $FE
TempMirror_PPUCTRL	.equ $FF

;ZP vars - Gameplay context (Mecha frog enemy)
MechaFrogTopIndex	.equ $94
MechaFrogMiddleIndex	.equ $95
MechaFrogBottomIndex	.equ $96
MechaFrogTopIndex2	.equ $9C
MechaFrogAnimTimer	.equ $A4
MechaFrogRejoinFlag	.equ $A6
MechaFrogRejoinTimer	.equ $A7
MechaFrogTopHP		.equ $AD
MechaFrogMiddleHP	.equ $AE
MechaFrogBottomHP	.equ $AF

;ZP vars - Gameplay context (Scroll anim/CHR bank anim)
BGGrayPipeVRAMAddrHi	.equ $93
BGDarkRoomMode		.equ $93
BGBallRollMode		.equ $94
BGRotRoomSaveScrollHi	.equ $95
BGPalAnimTimer		.equ $96
BGRotRoomSaveScrollX	.equ $96
BGCeilingSpikesMode	.equ $96
BGAnimMode		.equ $97
BGCeilingSpikesIndex	.equ $97
BGFrozenIceLayerTimer	.equ $97
BGGrayPipeVRAMAddrLo	.equ $A3
BGDarkRoomTimer		.equ $A3
BGCeilingSpikesTimer	.equ $A4
BGAnimTimer		.equ $A7
BGRotRoomDrawScrollHi	.equ $B5
BGRotRoomDrawScrollX	.equ $B6
BGGrayPipeMode		.equ $BB
BGDarkRoomVRAMAddrLo	.equ $BB
BGElevatorDirection	.equ $BF
BGMinibossSnakeEndFlag	.equ $BF
BGDarkRoomVRAMAddrHi	.equ $D3

;ZP vars - Dialog context
DialogLineClearIndex	.equ $94
DialogCursorX		.equ $95
DialogCursorY		.equ $96
DialogTextTimer		.equ $97
DialogDataPointer	.equ $9C
SceneSpeedDivIndex	.equ $9E
DialogFastTextFlag	.equ $9F
SceneTimer		.equ $A4
SceneLoopCount		.equ $A5
SceneCommandOffset	.equ $A6
SceneNextLevel		.equ $A7
SceneDataPointer	.equ $AC
SceneID			.equ $AE
DialogID		.equ $AF
DialogEndFlag		.equ $B4
DialogArrowFlashFlag	.equ $B5
SceneSpeedDiv		.equ $B6
SceneShipChaseMode	.equ $B7
SceneScrollX		.equ $BC
SceneScrollY		.equ $BD
SceneBlackTimer		.equ $BE
SceneColumn		.equ $BF
SceneDataByte		.equ $C4
DialogDataByte		.equ $C5
DialogAutoEnableFlag	.equ $CC
DialogAutoInputTimer	.equ $CD
DialogAutoEndTimers	.equ $CE
TempPasswordIndex	.equ $D4
TempPasswordLevels567	.equ $D5
SceneShipChaseFlag	.equ $D6
DialogClearFlag		.equ $D7

;WRAM vars
TempCHRBanks		.equ $0103
PausedFlag		.equ $0109
ReadyTimer		.equ $010A
JoypadUnmasked		.equ $010C
PlatformYPos		.equ $010D
BossEnemyIndex		.equ $010E
LevelsCompletedFlags	.equ $010F
FrozenIceLayerFlag	.equ $0110
Level5ExitElevator	.equ $0111
Level5ExitArea		.equ $0112
Level5ExitMode		.equ $0113
SecondVRAMStripIndex	.equ $0114
LegalWaitTimer		.equ $0114
TitleCursorPos		.equ $0114
VictoryGroundFlag	.equ $0114
DisableSideExitFlag	.equ $0115
SecondVRAMStripFlag	.equ $0116
EnemyGrabbingIndex	.equ $0117
DemoTimer		.equ $0119
DemoIndex		.equ $011B
DisableSoundLoadFlag	.equ $011C
ConveyorUpdateFlag	.equ $011D
GameplayFlag		.equ $011E
VRAMBuffer		.equ $0120
OAMBuffer		.equ $0200
CollisionBuffer		.equ $0300

;Enemy vars
Enemy_Flags		.equ $0500
Enemy_Y			.equ $0510
Enemy_X			.equ $0520
Enemy_Props		.equ $0530
Enemy_SpriteLo		.equ $0540
Enemy_SpriteHi		.equ $0550
Enemy_AnimTimer		.equ $0560
Enemy_Anim		.equ $0570
Enemy_AnimOffs		.equ $0580
Enemy_ID		.equ $0590
Enemy_HP		.equ $05A0
Enemy_CollWidth		.equ $05B0
Enemy_CollHeight	.equ $05C0
Enemy_XLo		.equ $05D0
Enemy_XVelHi		.equ $05E0
Enemy_XVelLo		.equ $05F0
Enemy_XAccel		.equ $0600
Enemy_YLo		.equ $0610
Enemy_YVelHi		.equ $0620
Enemy_YVelLo		.equ $0630
Enemy_YAccel		.equ $0640
Enemy_Temp0		.equ $0650
Enemy_Temp1		.equ $0660
Enemy_Temp2		.equ $0670
Enemy_Temp3		.equ $0680
Enemy_Temp4		.equ $0690
Enemy_Temp5		.equ $06A0
Enemy_Temp6		.equ $06B0
Enemy_Temp7		.equ $06C0

;Enemy vars - Title context
PasswordIndex		.equ $0600
PasswordBuffer		.equ $0640
PasswordDecodeBuffer	.equ $0648
TitleWaitTimer		.equ $067C

;WRAM vars
VerticalShipMouthFrame	.equ $06D0
VerticalShipMouthProps	.equ $06D7
CHRBanks		.equ $06E2
Mirror_PPUSCROLL_Y	.equ $06E8
Mirror_PPUSCROLL_X	.equ $06E9
Mirror_PPUCTRL		.equ $06EA
BeetleInWallOutFlag	.equ $06EB
GrabWallCooldownTimer	.equ $070F
PRNGDataSaveY		.equ $0710
DemoEndAllFlag		.equ $0711
PasswordHoldTimer	.equ $0712
DemoCreditsTimerHi	.equ $0714
DemoEndFlag		.equ $0715
DemoCreditsIndex	.equ $0716
DemoCreditsTimerLo	.equ $0716
DemoWaitMode		.equ $0717
DemoInputTimer		.equ $071D
DemoInputDownIndex	.equ $071E
DemoInputCurIndex	.equ $071F

;Sound vars
SoundPointersLo		.equ $0720
SoundPointersHi		.equ $0726
SoundBaseLength		.equ $072C
SoundReturnPtrLo	.equ $0732
SoundReturnPtrHi	.equ $0738
SoundRepeat1Counter	.equ $073E
SoundRepeat2Counter	.equ $0744
SoundRepeat1PtrLo	.equ $074A
SoundRepeat2PtrLo	.equ $0750
SoundRepeat1PtrHi	.equ $0756
SoundRepeat2PtrHi	.equ $075C
SoundControlFlags	.equ $0762
SoundID			.equ $0768
SoundTimerLo		.equ $076E
SoundTimerHi		.equ $0774
SoundPriority		.equ $077A
SoundOutFreqLo		.equ $0780
SoundOutFreqHi		.equ $0785
SoundFreqLo		.equ $078A
SoundFreqHi		.equ $078F
SoundVol		.equ $0794
SoundDuty		.equ $0799
SoundPitch		.equ $079E
SoundFade		.equ $07A2
SoundOctave		.equ $07A6
SoundPitchShift		.equ $07A9
SoundEchoDuty		.equ $07AC
SoundInst1		.equ $07AE
SoundEchoSettings	.equ $07B0
SoundEchoEndLo		.equ $07B2
SoundEchoEndHi		.equ $07B4
SoundEchoFadeTimer	.equ $07B6
SoundEchoFade		.equ $07B8
SoundInst2Multiplier	.equ $07BA
SoundInst2TimerStart	.equ $07BC
SoundInst2		.equ $07BE
SoundInst1Timer		.equ $07C0
SoundInst2Timer		.equ $07C2
SoundInst1Pointer	.equ $07C4
SoundInst2Pointer	.equ $07C6
SoundInst1RepeatPointer	.equ $07C8
SoundInst2RepeatPointer	.equ $07CA
SoundInst1RepeatCounter	.equ $07CC
SoundInst2RepeatCounter	.equ $07CE
SoundEchoTimer		.equ $07D0
SoundEchoAmount		.equ $07D2
SoundJumpTableSaveY	.equ $07D4
SoundJumpTableSaveX	.equ $07D5
SoundEchoBufferLo	.equ $07D6
SoundEchoBufferHi	.equ $07DE
SoundLoadID		.equ $07E6
SoundLoadCurChannel	.equ $07E7
SoundLoadNumChannels	.equ $07E8
SoundTriLinearTimer	.equ $07E9
SoundTriLinearReload	.equ $07EA
SoundCurChannel		.equ $07EB
SoundTempoCompare	.equ $07EC
SoundTempoTimer		.equ $07ED
SoundFadeoutTimer	.equ $07EE
SoundFadeoutCompare	.equ $07F1
SoundPausedFlag		.equ $07F3
SoundLoadPriority	.equ $07F4
SoundGlobalPitchShift	.equ $07F5

;;;;;;;;;;;;;;
;GAME DEFINES;
;;;;;;;;;;;;;;
ENEMY_PLAYERFIRE	.equ $00
ENEMY_MECHAFROGMIDDLE	.equ $01
ENEMY_MECHAFROGBOTTOM	.equ $02
ENEMY_BLINKYFIRE	.equ $03
ENEMY_ROTROOMARROW	.equ $04
ENEMY_TROOPER		.equ $05
ENEMY_ENEMYFIRE		.equ $06
ENEMY_TROOPER2		.equ $07
ENEMY_JENNYLIGHTBALL	.equ $08
ENEMY_BG8WAYSHOOTER	.equ $09
ENEMY_CATERPILLAR	.equ $0A
ENEMY_SPIDER		.equ $0B
ENEMY_BEEHIVE		.equ $0C
ENEMY_BEE		.equ $0D
ENEMY_SHIPFIN		.equ $0E
ENEMY_LEVEL7BOSSFRONTP2	.equ $0F
ENEMY_LIFEUP		.equ $10
ENEMY_POWERUP		.equ $11
ENEMY_1UP		.equ $12
ENEMY_BONUSCOIN		.equ $13
ENEMY_LIGHTNING		.equ $14
ENEMY_SWINGINGVINE	.equ $15
ENEMY_LEVEL1BOSS	.equ $16
ENEMY_FLOATINGLOGPLAT	.equ $17
ENEMY_BOULDERROLL	.equ $18
ENEMY_FLTLOGSPAWNER	.equ $19
ENEMY_FLOATINGLOGDUMMY	.equ $1A
ENEMY_SWINGINGVINEPLAT	.equ $1B
ENEMY_FISH		.equ $1C
ENEMY_BALANCEVINEPLAT	.equ $1D
ENEMY_BALANCEVINEMASK	.equ $1E
ENEMY_FALLINGTREEPLATL	.equ $1F
ENEMY_FALLINGTREEPLATR	.equ $20
ENEMY_SIDEFLOWER	.equ $21
ENEMY_FALLINGROCK	.equ $22
ENEMY_ROCKSMSPAWNER	.equ $23
ENEMY_SHIPDOWNLASER	.equ $24
ENEMY_SHIPMOUTH		.equ $25
ENEMY_LEVEL1BOSSBOULDER	.equ $26
ENEMY_TROOPERINICE	.equ $27
ENEMY_LAVABUBBLESPLASH	.equ $28
ENEMY_LAVABUBBLE	.equ $29
ENEMY_VOLCANO		.equ $2A
ENEMY_BGFIREARCH	.equ $2B
ENEMY_BGFIRESNAKE	.equ $2C
ENEMY_BOULDERROLLSPAWN	.equ $2D
ENEMY_TROOPERROLLING	.equ $2E
ENEMY_BOULDERPUSH	.equ $2F
ENEMY_GREENBALLDOT	.equ $30
ENEMY_LEVEL2BOSS	.equ $31
ENEMY_LEVEL2BOSSDOT	.equ $32
ENEMY_BGSNAKE		.equ $33
ENEMY_BGICEBERGCONVPLAT	.equ $34
ENEMY_TROOPERMELTINGICE	.equ $35
ENEMY_TROOPERJETPACK	.equ $36
ENEMY_TROOPERICESPIKE	.equ $37
ENEMY_TROOPERICEBLOCK	.equ $38
ENEMY_ICESPIKE		.equ $39
ENEMY_ICEBLOCK		.equ $3A
ENEMY_ROLLINGSPIKE	.equ $3B
ENEMY_ICEWATERDECOR	.equ $3C
ENEMY_SPRITEMASK	.equ $3D
ENEMY_LEVEL3BOSS	.equ $3E
ENEMY_L3BSMISSBGICEROCK	.equ $3F
ENEMY_FROZENINICE	.equ $40
ENEMY_L2BSEYESBGGRPIPE	.equ $41
ENEMY_ICICLE		.equ $42
ENEMY_TROOPERICICLE	.equ $43
ENEMY_BG3WAYSHOOTER	.equ $44
ENEMY_CRATERGUN		.equ $45
ENEMY_FLASHINGARROW	.equ $46
ENEMY_DIVEBOMBER	.equ $47
ENEMY_CRATERSNAKE	.equ $48
ENEMY_BLUESIDESPIKES	.equ $49
ENEMY_MINECART		.equ $4A
ENEMY_CRATERSNAKEPART	.equ $4B
ENEMY_SPIKEPARTICLES	.equ $4C
ENEMY_RESETMELTABLEICE	.equ $4D
ENEMY_LEVEL4BOSSP2	.equ $4E
ENEMY_BOSSMISSILEHOMING	.equ $4F
ENEMY_LEVEL4BOSSFIRE	.equ $50
ENEMY_LEVEL4BOSSP1	.equ $51
ENEMY_ASTEROID		.equ $52
ENEMY_ASTEROIDPLAT	.equ $53
ENEMY_VERTSHIPFIRE	.equ $54
ENEMY_BEHBGAREABGGLPIPE	.equ $55
ENEMY_CONVEYOR		.equ $56
ENEMY_TROOPERTRENCH	.equ $57
ENEMY_HYPNOJENNY	.equ $58
ENEMY_HYPNOWILLY	.equ $59
ENEMY_HYPNODEADEYE	.equ $5A
ENEMY_HYPNOFROG		.equ $5B
ENEMY_HYPNOFROGBEAM	.equ $5C
ENEMY_HYPNOJENNYLTBALL	.equ $5D
ENEMY_BGCHUTECRUSHER	.equ $5E
ENEMY_ARROWYOKUBLOCK	.equ $5F
ENEMY_YOKUBLOCKSPAWN	.equ $60
ENEMY_DARKROOM		.equ $61
ENEMY_BEETLEINWALL	.equ $62
ENEMY_CEILINGSLUG	.equ $63
ENEMY_BEETLEUPDOWN	.equ $64
ENEMY_CEILINGLASER	.equ $65
ENEMY_CAGEDPIG		.equ $66
ENEMY_SPIKEBUG		.equ $67
ENEMY_LAVAWORM		.equ $68
ENEMY_BGFAKEBLOCK	.equ $69
ENEMY_LEVEL6BOSS	.equ $6A
ENEMY_ASTEROIDFALL	.equ $6B
ENEMY_BGAPPEARINGSPIKES	.equ $6C
ENEMY_LAVAPLAT		.equ $6D
ENEMY_TANKERSIDESPIKES	.equ $6E
ENEMY_GRAVITYAREA	.equ $6F
ENEMY_BGGLASSROBOT	.equ $70
ENEMY_BACKGROUNDMONITOR	.equ $71
ENEMY_CONVEYORPLAT	.equ $72
ENEMY_ESCAPEPOD		.equ $73
ENEMY_TROOPERESCAPING	.equ $74
ENEMY_TROOPERGRABBING	.equ $75
ENEMY_BGGLASSPIPE	.equ $76
ENEMY_ESCAPEMBSHIP	.equ $77
ENEMY_ENEMYFIRE2	.equ $78
ENEMY_LEVEL7BOSSBACK	.equ $79
ENEMY_LEVEL7BOSSTOP	.equ $7A
ENEMY_LEVEL7BOSSFRONTP1	.equ $7B
ENEMY_TROOPJPSPAWNER	.equ $7C
ENEMY_ESCAPEFLAME	.equ $7D
ENEMY_ESCAPESHOOTER	.equ $7E
;Unused
ENEMY_MECHAFROG		.equ $80
ENEMY_ESCAPEMBSNAKE	.equ $81
ENEMY_LEVEL8BOSS	.equ $82
ENEMY_LEVEL8BOSSBOMB	.equ $83
ENEMY_CROCODILE		.equ $84
ENEMY_ROTROOMSHOOTER	.equ $85
ENEMY_CROCODILESPAWNER	.equ $86

EF_VISIBLE	.equ $01
EF_HITENEMY	.equ $02
EF_HITBULLET	.equ $04
EF_PRIORITY	.equ $08
EF_PLATFORM	.equ $10
EF_NOANIM	.equ $20
EF_INVINCIBLE	.equ $40
EF_ACTIVE	.equ $80

SE_CLOSEDHHAT	.equ $01
SE_OPENHHAT	.equ $02
SE_BASSNOISE	.equ $03
SE_SNARENOISE	.equ $04
SE_LAND		.equ $05
SE_JUMP		.equ $06
SE_PLAYERSHOOT1	.equ $07
SE_PLAYERSHOOT2	.equ $08
SE_PLAYERSHOOT3	.equ $09
SE_LIGHTNING	.equ $0A
SE_BUZZ		.equ $0B
SE_ICEBLOCKLAND	.equ $0C
SE_SHOOTLASER	.equ $0D
SE_WHIRSHORT	.equ $0E
SE_SHOOTFRONT	.equ $0F
SE_CHARGING	.equ $10
SE_CHARGING2	.equ $11
SE_TREEPLATFALL	.equ $12
SE_VINEPLATFALL	.equ $13
SE_SPLASH	.equ $14
SE_MELTINGICE	.equ $15
SE_BGFIREARCH	.equ $16
SE_BGFIRESNAKE	.equ $17
SE_GRAVITYUP	.equ $18
SE_GRAVITYDOWN	.equ $19
SE_MINECARTMOVE	.equ $1A
SE_BGSNAKE	.equ $1B
SE_BGGLASSROBOT	.equ $1C
SE_MACHINEGUN	.equ $1D
SE_BGFAKEBLOCK	.equ $1E
SE_BEETLEINWALL	.equ $1F
SE_ENEMYGRAB	.equ $20
SE_BGCHUTECRUSH	.equ $21
SE_JENNYLTBALL	.equ $22
SE_DEADEYEGRAB	.equ $23
SE_WILLYSHOOT	.equ $24
SE_BLINKYFLY	.equ $25
SE_MINECARTSLOW	.equ $26
SE_ELEVATOR	.equ $27
SE_ENEMYINVIN	.equ $28
SE_PLAYERHIT	.equ $29
SE_ENEMYKILL	.equ $2A
SE_ENEMYHIT	.equ $2B
SE_CRASH	.equ $2C
SE_DIVEBOMBER	.equ $2D
SE_WHIRLASER1	.equ $2E
SE_WHIRLASER2	.equ $2F
SE_BALLROLL	.equ $30
SE_WHIRLONG	.equ $31
SE_BLAST	.equ $32
SE_L6FALL	.equ $33
SE_BREAKGLASS	.equ $34
SE_HYPNOTIZE	.equ $35
SE_L6LAND	.equ $36
SE_POWERUP	.equ $37
SE_1UP		.equ $38
SE_LIFEUP	.equ $39
SE_BONUSCOIN	.equ $3A
SE_PASSSCENE	.equ $3B
SE_BOSSKILL	.equ $3C
SE_CURSMOVE	.equ $3D
SE_SELECT	.equ $3E
SE_PASSINVALID	.equ $3F
SE_TYPING	.equ $40
SE_PAUSE	.equ $41
;Unused duplicate of level 1
MUSIC_LEVEL1	.equ $43
MUSIC_LEVEL2	.equ $44
MUSIC_LEVEL3	.equ $45
MUSIC_LEVEL4	.equ $46
MUSIC_LEVEL5	.equ $47
MUSIC_LEVEL6	.equ $48
MUSIC_LEVEL8	.equ $49
MUSIC_LEVEL7	.equ $4A
MUSIC_BOSS	.equ $4B
MUSIC_BOSS2	.equ $4C
MUSIC_TITLE	.equ $4D
MUSIC_SCENE0	.equ $4E
MUSIC_SCENE1	.equ $4F
MUSIC_SCENE2	.equ $50
MUSIC_STAGESEL	.equ $51
MUSIC_RESCUE	.equ $52
MUSIC_DEATH	.equ $53
MUSIC_GAMEOVER	.equ $54
MUSIC_CLEAR	.equ $55
MUSIC_CREDITS	.equ $56
MUSIC_THEEND	.equ $57
;Unused duplicates of DMC snare drum
;
;
;
DMC_SNARE	.equ $5C
DMC_BASS	.equ $5D

SF_SNDEFF	.equ $01
SF_INSUB	.equ $02
SF_PORTA	.equ $04
SF_SWEEP	.equ $08
SF_LOOP2	.equ $10
SF_REPEAT	.equ $20
SF_REST		.equ $40
SF_TIE		.equ $80
